[
                "run_release_funds",
                "run_custom_outside_trading_strategy",
                "run_custom_dividend_low_wave_strategy",
                "run_custom_bond_trend_rotation_strategy",
                "run_custom_outside_trading_strategy",
                "run_custom_dividend_low_wave_strategy",
                "run_custom_bond_trend_rotation_strategy",
                "run_buy_bonds_to_deposit_funds"
                ],